l_zh_TW:
  ConfigTitle: "配置"
  Group_Directories: "目錄"
  Group_Plugins: "插件"
  GameDir_Title: "遊戲目錄"
  GameDir_Desc: "鋼鐵雄心 4 安裝路徑"
  DocDir_Title: "文檔目錄"
  DocDir_Desc: "鋼鐵雄心 4 文檔路徑"
  ReselectBtn: "重新選擇"
  ModDir_Title: "當前 Mod"
  ModDir_Desc: "已選 Mod 路徑"
  Plugins_Empty: "目前沒有已加載插件。"
  Plugins_Loaded: "已加載"
  Plugins_MetadataOnly: "僅元資料"
  Plugins_LoadedVersion: "版本：%1"
