l_ru_RU:
  ConfigTitle: "Конфигурация"
  Group_Directories: "Каталоги"
  Group_Plugins: "Плагины"
  GameDir_Title: "Каталог игры"
  GameDir_Desc: "Путь к установке HOI4"
  DocDir_Title: "Каталог документов"
  DocDir_Desc: "Путь к папке документов HOI4"
  ReselectBtn: "Выбрать заново"
  ModDir_Title: "Текущий мод"
  ModDir_Desc: "Путь к выбранному моду"
  Plugins_Empty: "Плагины не загружены."
  Plugins_Loaded: "Загружено"
  Plugins_MetadataOnly: "Только метаданные"
  Plugins_LoadedVersion: "Версия: %1"