l_ru_RU:
  SettingsTitle: "Настройки"
  Group_Interface: "Интерфейс"
  Group_Accessibility: "Доступность"
  Group_Debug: "Отладка"
  Group_About: "О программе"
  Theme_Title: "Режим темы"
  Theme_Desc: "Выберите внешний вид приложения"
  Lang_Title: "Язык"
  Lang_Desc: "Для применения изменений требуется перезапуск"
  Debug_Title: "Показывать использование ресурсов"
  Debug_Desc: "Показывать оверлей использования памяти"
  Log_Title: "Журналы"
  Log_Desc: "Открыть каталог журналов приложения"
  Log_Btn: "Открыть журналы"
  MaxLogs_Title: "Макс. файлов журналов"
  MaxLogs_Desc: "Количество хранимых файлов журналов"
  Sidebar_Title: "Компактная боковая панель"
  Sidebar_Desc: "Автоматически сворачивать боковую панель"
  AboutHeader: "О программе"
  GithubLink: "Репозиторий GitHub"
  UserAgreementBtn: "Пользовательское соглашение"
  OpenSourceBtn: "Библиотеки с открытым исходным кодом ▼"
  Theme_System: "Системная"
  Theme_Light: "Светлая"
  Theme_Dark: "Темная"
  PinToStart_Title: "Закрепить в меню «Пуск»"
  PinToStart_Desc: "Создать ярлык в меню «Пуск»"
  ClearCache_Title: "Очистить кэш приложения"
  ClearCache_Desc: "Приложение будет автоматически закрыто после очистки"