l_ru_RU:
  SettingsTitle: "Настройки"
  Group_Interface: "Интерфейс"
  Group_Accessibility: "Доступность"
  Group_Debug: "Отладка"
  Group_About: "О программе"
  Theme_Title: "Режим темы"
  Theme_Desc: "Выберите внешний вид приложения"
  InterfaceLanguage_Title: "Язык интерфейса"
  InterfaceLanguage_Desc: "Используется для отображения текста интерфейса в приложении"
  GameLanguage_Title: "Язык игры"
  GameLanguage_Desc: "Используется для внутриигровых локализованных названий"
  Debug_Title: "Показывать использование ресурсов"
  Debug_Desc: "Показывать оверлей использования памяти"
  Log_Title: "Журналы"
  Log_Desc: "Открыть каталог журналов приложения"
  Log_Btn: "Смотреть"
  MaxLogs_Title: "Макс. файлов журналов"
  MaxLogs_Desc: "Количество хранимых файлов журналов"
  Sidebar_Title: "Компактная боковая панель"
  Sidebar_Desc: "Автоматически сворачивать боковую панель"
  DisplayMode_Title: "Режим отображения"
  DisplayMode_Desc: "Выберите оконный или полноэкранный режим"
  DisplayMode_Window: "Окно"
  DisplayMode_Fullscreen: "Полный экран"
  DisplayScreen_Title: "Монитор"
  DisplayScreen_Desc: "Выберите целевой дисплей"
  DisplayScreen_Button: "Дисплей %1"
  DisplayScreen_ButtonNone: "Нет дисплея"
  DisplayScreen_Item: "Дисплей %1 - %2 (%3 x %4)"
  DisplayScreenChooser_Cancel: "Отмена"
  DisplayScreenChooser_Confirm: "ОК"
  Resolution_Title: "Разрешение"
  Resolution_Desc: "Размер окна для выбранного дисплея"
  AboutHeader: "О программе"
  GithubLink: "Официальный сайт"
  UserAgreementBtn: "Пользовательское соглашение"
  OpenSourceBtn: "Библиотеки с открытым исходным кодом ▼"
  Theme_System: "Системная"
  Theme_Light: "Светлая"
  Theme_Dark: "Темная"
  PinToStart_Title: "Закрепить в меню «Пуск»"
  PinToStart_Desc: "Создать ярлык в меню «Пуск»"
  PinToStart_Btn: "Закрепить"
  ClearCache_Title: "Очистить кэш приложения"
  ClearCache_Desc: "Приложение будет автоматически закрыто после очистки"
  ClearCache_Btn: "Очистить"
