if(EXISTS "${APE_SOURCE}")
    file(COPY "${APE_SOURCE}" DESTINATION "${APE_DEST_DIR}")
    if(NOT "${APE_DEST_NAME}" STREQUAL "")
        get_filename_component(APE_SOURCE_NAME "${APE_SOURCE}" NAME)
        if(NOT "${APE_SOURCE_NAME}" STREQUAL "${APE_DEST_NAME}")
            file(RENAME "${APE_DEST_DIR}/${APE_SOURCE_NAME}" "${APE_DEST_DIR}/${APE_DEST_NAME}")
        endif()
    endif()
endif()
