if(NOT DEFINED APE_BUILD_DIR)
    message(FATAL_ERROR "APE_BUILD_DIR is required.")
endif()

if(NOT DEFINED APE_SOURCE_DIR)
    message(FATAL_ERROR "APE_SOURCE_DIR is required.")
endif()

set(APE_CACHE_FILE "${APE_BUILD_DIR}/CMakeCache.txt")
if(NOT EXISTS "${APE_CACHE_FILE}")
    message(FATAL_ERROR "CMakeCache.txt not found: ${APE_CACHE_FILE}")
endif()

function(ape_compute_dll_revision dll_path out_var)
    if(NOT EXISTS "${dll_path}")
        message(FATAL_ERROR "DLL not found: ${dll_path}")
    endif()

    file(SHA256 "${dll_path}" dll_hash)
    string(SUBSTRING "${dll_hash}" 0 4 dll_hash_prefix)
    math(EXPR dll_revision "0x${dll_hash_prefix} % 65535")
    set(${out_var} "${dll_revision}" PARENT_SCOPE)
endfunction()

function(ape_update_cache_entry cache_path entry_name entry_value)
    file(READ "${cache_path}" cache_content)
    string(REGEX REPLACE "(\n|^)${entry_name}:STRING=[^\n]*" "\\1${entry_name}:STRING=${entry_value}" updated_cache_content "${cache_content}")

    if("${updated_cache_content}" STREQUAL "${cache_content}")
        string(APPEND updated_cache_content "\n${entry_name}:STRING=${entry_value}\n")
    endif()

    file(WRITE "${cache_path}" "${updated_cache_content}")
endfunction()

function(ape_resolve_dll_path build_dir dll_name out_var)
    set(dll_path "${build_dir}/${dll_name}")
    if(NOT EXISTS "${dll_path}")
        set(dll_path "${build_dir}/main/${dll_name}")
    endif()

    if(NOT EXISTS "${dll_path}")
        message(FATAL_ERROR "DLL not found in build output: ${dll_name}")
    endif()

    set(${out_var} "${dll_path}" PARENT_SCOPE)
endfunction()

ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.core.dll" APE_CORE_DLL)
ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.tool.dll" APE_TOOL_DLL)
ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.plugin.dll" APE_PLUGIN_DLL)
ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.logger.dll" APE_LOGGER_DLL)
ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.config.dll" APE_CONFIG_DLL)
ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.localization.dll" APE_LOCALIZATION_DLL)
ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.messageBox.dll" APE_MESSAGE_BOX_DLL)
ape_resolve_dll_path("${APE_BUILD_DIR}" "APEHOI4ToolStudio.file.dll" APE_FILE_DLL)

ape_compute_dll_revision("${APE_CORE_DLL}" APE_CORE_REVISION)
ape_compute_dll_revision("${APE_TOOL_DLL}" APE_TOOL_REVISION)
ape_compute_dll_revision("${APE_PLUGIN_DLL}" APE_PLUGIN_REVISION)
ape_compute_dll_revision("${APE_LOGGER_DLL}" APE_LOGGER_REVISION)
ape_compute_dll_revision("${APE_CONFIG_DLL}" APE_CONFIG_REVISION)
ape_compute_dll_revision("${APE_LOCALIZATION_DLL}" APE_LOCALIZATION_REVISION)
ape_compute_dll_revision("${APE_MESSAGE_BOX_DLL}" APE_MESSAGE_BOX_REVISION)
ape_compute_dll_revision("${APE_FILE_DLL}" APE_FILE_REVISION)

ape_update_cache_entry("${APE_CACHE_FILE}" "APE_CORE_VERSION_REVISION" "${APE_CORE_REVISION}")
ape_update_cache_entry("${APE_CACHE_FILE}" "APE_TOOL_VERSION_REVISION" "${APE_TOOL_REVISION}")
ape_update_cache_entry("${APE_CACHE_FILE}" "APE_PLUGIN_VERSION_REVISION" "${APE_PLUGIN_REVISION}")
ape_update_cache_entry("${APE_CACHE_FILE}" "APE_LOGGER_VERSION_REVISION" "${APE_LOGGER_REVISION}")
ape_update_cache_entry("${APE_CACHE_FILE}" "APE_CONFIG_VERSION_REVISION" "${APE_CONFIG_REVISION}")
ape_update_cache_entry("${APE_CACHE_FILE}" "APE_LOCALIZATION_VERSION_REVISION" "${APE_LOCALIZATION_REVISION}")
ape_update_cache_entry("${APE_CACHE_FILE}" "APE_MESSAGE_BOX_VERSION_REVISION" "${APE_MESSAGE_BOX_REVISION}")
ape_update_cache_entry("${APE_CACHE_FILE}" "APE_FILE_VERSION_REVISION" "${APE_FILE_REVISION}")

message(STATUS "Updated library revisions from built DLL hashes:")
message(STATUS "  APE_CORE_VERSION_REVISION=${APE_CORE_REVISION}")
message(STATUS "  APE_TOOL_VERSION_REVISION=${APE_TOOL_REVISION}")
message(STATUS "  APE_PLUGIN_VERSION_REVISION=${APE_PLUGIN_REVISION}")
message(STATUS "  APE_LOGGER_VERSION_REVISION=${APE_LOGGER_REVISION}")
message(STATUS "  APE_CONFIG_VERSION_REVISION=${APE_CONFIG_REVISION}")
message(STATUS "  APE_LOCALIZATION_VERSION_REVISION=${APE_LOCALIZATION_REVISION}")
message(STATUS "  APE_MESSAGE_BOX_VERSION_REVISION=${APE_MESSAGE_BOX_REVISION}")
message(STATUS "  APE_FILE_VERSION_REVISION=${APE_FILE_REVISION}")